### PR TITLE
project: import `otk`

### PR DESCRIPTION
**Pull request by supakeen**
Import the documentation for `otk`.

### CODE REVIEW

**Comment by ochosi** [comment]
I guess this isn't ready yet, the import scripts still need to be updated, right?

**Comment by supakeen** [comment]
> I guess this isn't ready yet, the import scripts still need to be updated, right?

What do you mean? There's no need to import the README as the project has a direct `index.md`. And there's no need to import other things a-la osbuild modules either? :)

**Comment by ochosi** [comment]
But how will it get updated? (Sorry, maybe I'm missing something obvious)

**Comment by supakeen** [comment]
> But how will it get updated? (Sorry, maybe I'm missing something obvious)

It won't. The documentation will be removed from the `otk` repository and included here instead much like the documentation for other projects in this repository.

If you want I can adjust this PR to instead use the pipelines to auto pull in the `doc/` subdirectory of the `otk` repository but that's different from how the other pages work here.

We only pull in the README's of a few selected projects and then we autogenerate the content of `modules/` under `osbuild` here.

**Comment by ochosi** [comment]
> > But how will it get updated? (Sorry, maybe I'm missing something obvious)
> 
> It won't. The documentation will be removed from the `otk` repository and included here instead much like the documentation for other projects in this repository.
> 
> If you want I can adjust this PR to instead use the pipelines to auto pull in the `doc/` subdirectory of the `otk` repository but that's different from how the other pages work here.
> 
> We only pull in the README's of a few selected projects and then we autogenerate the content of `modules/` under `osbuild` here.
I don't really agree - we do pull [multiple pages per project](https://github.com/osbuild/osbuild.github.io/blob/main/readme-list). That is most of the 'developer guide' pages that this PR also targets.

The goal of the importer was to keep as many of the docs as possible with the code. This should help with getting the docs updated (e.g. how to install) when the project changes.

Is there a reason for otk to deviate from this or am I missing something?

**Comment by supakeen** [comment]
> > > But how will it get updated? (Sorry, maybe I'm missing something obvious)
> > 
> > 
> > It won't. The documentation will be removed from the `otk` repository and included here instead much like the documentation for other projects in this repository.
> > If you want I can adjust this PR to instead use the pipelines to auto pull in the `doc/` subdirectory of the `otk` repository but that's different from how the other pages work here.
> > We only pull in the README's of a few selected projects and then we autogenerate the content of `modules/` under `osbuild` here.
> > I don't really agree - we do pull [multiple pages per project](https://github.com/osbuild/osbuild.github.io/blob/main/readme-list). That is most of the 'developer guide' pages that this PR also targets.
> 
> The goal of the importer was to keep as many of the docs as possible with the code. This should help with getting the docs updated (e.g. how to install) when the project changes.
> 
> Is there a reason for otk to deviate from this or am I missing something?

There is no deviation here right? 

This is following the status quo of how the documentation for `osbuild`, etc work. Their documents live in this repository; and we [only import their READMEs](https://github.com/osbuild/osbuild.github.io/blob/main/.github/workflows/pull.yml#L25) and in the `osbuild` special case we also [pull the module documentation](https://github.com/osbuild/osbuild.github.io/blob/main/.github/workflows/pull.yml#L30) but for example the [rest of its docs](https://github.com/osbuild/osbuild.github.io/tree/main/docs/developer-guide/02-projects/osbuild) live in *this* repository.

Same goes for the "on premises" and "hosted" content though I guess those live across tools.

I'd be happy to expand the github action to instead pull the `docs` subdirectory directly from `otk` and place it here if that's how we want to do this in the future.

**Comment by thozza** [comment]
I agree with @ochosi that keeping the documentation in the OTK repository and importing it regularly would be much better. All the on-prem / service documentation in this repository is in it for historical reasons (it used to live outside of `osbuild-composer` and other repositories since the beginning) and sometimes because the topic spans multiple projects (repositories). This does not seem to be the case with OTK, so importing should be fine.

**Comment by supakeen** [comment]
@thozza Thanks for your review then I'll rewrite this PR to instead pull in the directory.

**Comment by supakeen** [comment]
@ochosi / @thozza this should be more in line with expectations :)

**Review by ochosi — CHANGES_REQUESTED** [review]
@supakeen  Can't we use https://github.com/osbuild/osbuild.github.io/blob/main/scripts/pull_readmes.py instead of adding a new script to pull?

Unless I'm missing something, it should be enough to update the mapping here: https://github.com/osbuild/osbuild.github.io/blob/main/readme-list

**Comment by supakeen** [comment]
> @supakeen Can't we use https://github.com/osbuild/osbuild.github.io/blob/main/scripts/pull_readmes.py instead of adding a new script to pull?
> 
> Unless I'm missing something, it should be enough to update the mapping here: https://github.com/osbuild/osbuild.github.io/blob/main/readme-list

We would need to update the mapping for each file from `otk/doc` we want included and always PR here if we add new files to `otk/doc`. Didn't seem like a nice workflow to me due to a lot of double bookkeeping.

**Review by thozza — APPROVED** [review]
FWIW, I'm OK with adding a dedicated script to pull OTK documentation. It is short and simple.

There's however one warning:
```
Warning:  Docusaurus found broken anchors!

Please check the pages of your site in the list below, and make sure you don't reference any anchor that does not exist.
Note: it's possible to ignore broken anchors with the 'onBrokenAnchors' Docusaurus configuration, and let the build pass.

Exhaustive list of all broken anchors found:
- Broken anchor on source page path = /docs/developer-guide/projects/otk/omnifest/:
   -> linking to /docs/developer-guide/projects/otk/omnifest/directive#otktarget
```

I didn't investigate it further, but this is probably something to fix in the OTK repository.

**Comment by supakeen** [comment]
> FWIW, I'm OK with adding a dedicated script to pull OTK documentation. It is short and simple.
> 
> There's however one warning:
> 
> ```
> Warning:  Docusaurus found broken anchors!
> 
> Please check the pages of your site in the list below, and make sure you don't reference any anchor that does not exist.
> Note: it's possible to ignore broken anchors with the 'onBrokenAnchors' Docusaurus configuration, and let the build pass.
> 
> Exhaustive list of all broken anchors found:
> - Broken anchor on source page path = /docs/developer-guide/projects/otk/omnifest/:
>    -> linking to /docs/developer-guide/projects/otk/omnifest/directive#otktarget
> ```
> 
> I didn't investigate it further, but this is probably something to fix in the OTK repository.

Ah yes, that needs to be fixed there: https://github.com/osbuild/otk/pull/292

**Review by ochosi — APPROVED** [review]
I guess the same double-book keeping is necessary in all of our repositories.
I assumed it wouldn't matter much because we don't add new docs _that frequently_.

That's different with otk at this point so the additional script is fine.

**Pull request merged**
